remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "neon"

plugins:
  - jekyll-include-cache

# Site settings
title: Your Blog Title
subtitle: Your Blog Subtitle
name: Your Name
description: "A brief description of your blog"
url: "https://yourdomain.com"
baseurl: ""
repository: "yourusername/yourusername.github.io"
logo: "/assets/images/logo.png"
teaser: "/assets/images/teaser.jpg"
masthead_title: "Your Custom Masthead Title"
words_per_minute: 200

# Site Author
author:
  name: "Your Name"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Your bio goes here. It can be a short description about you."
  location: "Your Location"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://yourdomain.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/yourusername"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yourusername"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/yourusername"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yourusername"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: America/New_York

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development